### PR TITLE
Landscape Mode Now Supported

### PR DESCRIPTION
**Pull request by parjanyaacoder**
Screenshot_20191230-082429_onRoad

Screenshot_20191230-082526_onRoad

Now the app supports Landscape Mode Also.Fixes Issue#48

### CODE REVIEW

**Comment by thebishaldeb** [comment]
Add images

**Comment by thebishaldeb** [comment]
And make  sure the content do not get messed up

**Comment by parjanyaacoder** [comment]
Can we open a new issue for all the activities in which the contents are getting messed up.These activities need redesigning to work properly in Landscape mode.We can look into it after you merge this pr.

**Comment by thebishaldeb** [comment]
We do not want one PR to solve one problem and create another. It should not give rise to other problems.

**Comment by parjanyaacoder** [comment]
So can I open a new issue for all contributors to redesign the activity page in which contents are getting mixed up in Landscape Mode

**Comment by thebishaldeb** [comment]
Nope. This PR should finish them off, I mean those changes.

**Pull request closed without merging**
