### PR TITLE
Auth Bug fix

### LINKED ISSUE #44: BUG - Login Auth
Found out a bug. 
Whenever we switch activities in app, it redirects to Auth. 
Should be fixed.

### PR DESCRIPTION
**Pull request by Sarthak2601**
Fixes #44 

Fixed the code that caused bug. 
Created new java file to manage Auth.

### CODE REVIEW

**Comment by thebishaldeb** [comment]
Remove conflicts

**Comment by Sarthak2601** [comment]
@thebishaldeb Resolved.

**Comment by s-ayush2903** [comment]
@Sarthak2601 There is no need to add a new activity, already there are many, as many activities in an app makes it slower and apk larger. Handle the same using fragments.  And one more thing, don't add so many useless commits in an MR squash/fixup them all to a single one

**Review by s-ayush2903 — CHANGES_REQUESTED** [review]
@Sarthak2601 There is no need to add a new activity, already there are many, as many activities in an app makes it slower and apk larger. Handle the same using fragments.  And one more thing, don't add so many useless commits in an MR squash/fixup them all to a single one

**Comment by Sarthak2601** [comment]
@s-ayush2903 
First of all, none of the commits is useless. Commit no. 1 and 2 fix bugs and the 3rd one is resolving of merge conflicts. 
Secondly, If I don't add another activity then Auth will pop up every time we switch to home activity. As far as the app size factor is to be considered, we can delete 2 activities - Login and Register as they are useless with the incoming of the new Auth system. So 1 new activity while deleting two.. is it a loss or a profit ? I think profit.

**Comment by Sarthak2601** [comment]
@s-ayush2903 Also, as per the rules of NWoC, students are not allowed to review PR's of other students. It would be really appreciable if you follow them. 
For reference: https://github.com/NJACKWinterOfCode/Get-Started

**Comment by s-ayush2903** [comment]
Chill baby, take it easy!

**Comment by thebishaldeb** [comment]
@s-ayush2903 Do not review others' PRs as you are also a participant. Also if there is any problem, please talk in the gitter channel, this is not the right place.

**Comment by s-ayush2903** [comment]
> @s-ayush2903 Do not review others' PRs as you are also a participant. Also if there is any problem, please talk in the gitter channel, this is not the right place.

@all_participants okay, Chill!!😎 😎

**Pull request merged**
